name: Multiverse-SignPortals
main: com.onarandombox.MultiverseSignPortals.MultiverseSignPortals
authors: ['Rigby','fernferret']
version: maven-version-number
api-version: 1.13
depend: ['Multiverse-Core']