name: Manually upload release to dev.bukkit.org

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release to upload'
        required: true

jobs:
  manually_upload_dbo_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifact
        id: release-artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ github.event.inputs.version }}
          file: multiverse-signportals-${{ github.event.inputs.version }}.jar

      - name: Upload to dev.bukkit.org
        uses: Multiverse/http-request-action@debug
        with:
          url: https://dev.bukkit.org/api/projects/31376/upload-file
          method: POST
          contentType: multipart/form-data
          customHeaders: '{ "X-Api-Token": "${{ secrets.DBO_UPLOAD_API_TOKEN }}" }'
          files: '{ "file": "${{ github.workspace }}/multiverse-signportals-${{ github.event.inputs.version }}.jar" }'
          escapeData: true
          data: >-
            {
              "metadata": '{
                "changelog": "${{ steps.release-artifact.outputs.body }}",
                "changelogType": "markdown",
                "releaseType": "release",
                "displayName": "${{ github.event.inputs.version }}",
                "gameVersions": ["9561", "9560", "9261", "9190", "9016", "8897", "8849", "8503", "7915", "7667", "7330", "7105"],
                "relations": {
                  "projects": [
                    {
                      "slug": "multiverse-core",
                      "type": "requiredDependency"
                    }
                  ]
                }
              }'
            }

# Bukkit Version IDs
# 9561: 1.19.3
# 9560: 1.19.2
# 9261: 1.19.1
# 9190: 1.19
# 9016: 1.18.2
# 8897: 1.18.1
# 8849: 1.18
# 8503: 1.17
# 7915: 1.16
# 7667: 1.15
# 7330: 1.14
# 7105: 1.13
